name: Build and Publish Helm container

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and test Helm container
      run: |
        GIT_BRANCH=${GITHUB_REF#refs/heads/} make docker_build
        GIT_BRANCH=${GITHUB_REF#refs/heads/} make test
    - name: Docker meta
      if: ${{ startsWith(github.ref, 'refs/heads/m') || startsWith(github.ref, 'refs/heads/v') }}
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: lachlanevenson/k8s-helm
        tag-semver: |
          {{raw}}
    - name: Set up QEMU
      if: ${{ startsWith(github.ref, 'refs/heads/m') || startsWith(github.ref, 'refs/heads/v') }}
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      if: ${{ startsWith(github.ref, 'refs/heads/m') || startsWith(github.ref, 'refs/heads/v') }}
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      if: ${{ startsWith(github.ref, 'refs/heads/m') || startsWith(github.ref, 'refs/heads/v') }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and publish multi-arch Helm container
      if: ${{ startsWith(github.ref, 'refs/heads/m') || startsWith(github.ref, 'refs/heads/v') }}
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/s390x,linux/arm64,linux/ppc64le
        push: true
        tags: |
          ${{ github.ref != 'refs/heads/master' && steps.docker_meta.outputs.tags || '' }}
          ${{ github.ref == 'refs/heads/master' && 'lachlanevenson/k8s-helm:latest' || '' }}
        labels: ${{ steps.docker_meta.outputs.labels }}
